name: Android CI

on:
  push:
    branches:
      - '*'
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
  # detekt:
  #   name: Static Code Analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "checkout"
  #       uses: actions/checkout@master

  #     - name: "detekt"
  #       uses: natiginfo/action-detekt-all@1.23.7