name: Android CI

on:
  push:
    branches:
      - '*'
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: "Ktlint"
        uses: lucasnlm/ktlint-action@master
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.7