name: Android CI

on:
  # push:
  #   branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master
